# YAML script for the CI/CD execution for elPaSo
#
# Author: Harikrishnan Sreekumar, Institute for Acoustics, TU Braunschweig, Germany

# elPaSo CI/CD stages

stages:
 - build
 - tests
 - documentation
 - deploy

variables:
  ELPASO_DOCKER_REGISTRY_IMG_GNU: "git.rz.tu-bs.de:4567/akustik/elpaso-core/elpasocore-baseimage-ubuntu-x64:23.01.1"
  ELPASO_DOCKER_REGISTRY_IMG_INTEL: "localhost:5000/elpaso-intel-ubuntu-x64:22.12.1"
  ELPASO_DOCKER_IMG_GNU: "git.rz.tu-bs.de:4567/akustik/elpaso-core/elpasocore:latest"
  DOCKER_GIT_DIR_GNU: /builds/elPaSo/gnu/
  DOCKER_GIT_DIR_INTEL: /builds/elPaSo/intel/
  ELPASO_VERSION: 23.05.1

# include projects
include:
 - .gitlab-ci-pipeline-gnu.yml
 - .gitlab-ci-pipeline-intel.yml

docu-manual:
  stage: documentation
  image: python:3.10-slim
  script:
    - pip install -U jupyter-book
    - cd doc
    - jupyter-book clean .
    - jupyter-book build .
  artifacts:
    paths:
      - doc/_build/

pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv doc/_build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

docu-doxygen:
  image: git.rz.tu-bs.de:4567/akustik/elpaso-core/tubslatex-elpaso-ci:23.01.1
  stage: documentation
  variables:
    GIT_CLONE_PATH: $DOCKER_GIT_DIR_GNU
  script:
    - cd $DOCKER_GIT_DIR_GNU/doc/doxygen
    - doxygen Doxyfile
    - cd doxyout/latex
    - make
    - mv refman.pdf $DOCKER_GIT_DIR_GNU/elpasoCore-docu-doxygen.pdf
  artifacts:
    name: elpasoCore_docs_Doxygen
    when: always
    paths:
      - elpasoCore-docu-doxygen.pdf
  tags:
    - Ubuntu
    - DockerExecutor
