SET(SUBDIRPATH material/structure/isotrop/linear/elastic) 
SET(OPTION_LABEL BUILD_Material_Structure_Isotrop_Linear_Elastic)

SET(CURRENT_DIR ${SOURCE_ELPASO}/${SUBDIRPATH})

OPTION(${OPTION_LABEL} "${CURRENT_DIR}" ON)
IF(${OPTION_LABEL})
   COLLECT_PACKAGE_DATA( ${CURRENT_DIR} ${SUBDIRPATH} ALL_SOURCES)
ENDIF(${OPTION_LABEL})