# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "elPaSo Documentation"
author: "Technische Universität Braunschweig, Institut für Akustik"
logo: logo/InA-TECH-elPaSo-rgb.png
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://git.rz.tu-bs.de/akustik/elPaSo-Core  # Online location of your book
  #path_to_book: "" # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: logo/ina_logo_rgb_no_text_16x16.ico
  use_issues_button: false
  use_repository_button: true
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  analytics:
    google_analytics_id = ''

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: gitlab  

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  jupyterhub_url            : "https://jupyter.rz.tu-bs.de"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true
  
extra_extensions:
  - sphinx_click.ext
  - sphinx_inline_tabs
  - sphinxext.rediraffe
  - sphinx_proof
  - sphinx_examples

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist