SET(SUBDIRPATH misc/hdf5) 
SET(OPTION_LABEL BUILD_Miscellaneous_HDF5)

SET(CURRENT_DIR ${SOURCE_ELPASO}/${SUBDIRPATH})

IF(INCLUDE_HDF5)
   OPTION(${OPTION_LABEL} "${CURRENT_DIR}" ON)
   IF(${OPTION_LABEL})
      COLLECT_PACKAGE_DATA( ${CURRENT_DIR} ${SUBDIRPATH} ALL_SOURCES)
   ENDIF(${OPTION_LABEL})
ELSE()
   MESSAGE(WARNING "> [EXCLUDED] Available module HDF5")
ENDIF()