SET(SUBDIRPATH basics) 
SET(OPTION_LABEL BUILD_Basics)

SET(CURRENT_DIR ${SOURCE_ELPASO}/${SUBDIRPATH})
OPTION(${OPTION_LABEL} "${CURRENT_DIR}" ON)
IF(${OPTION_LABEL})
   COLLECT_PACKAGE_DATA( ${CURRENT_DIR} ${SUBDIRPATH} ALL_SOURCES)
ENDIF(${OPTION_LABEL})

#additional includes
INCLUDE(${SOURCE_ELPASO}/basics/exceptions/CMakePackage.cmake)
INCLUDE(${SOURCE_ELPASO}/basics/mpi/CMakePackage.cmake)
INCLUDE(${SOURCE_ELPASO}/basics/watch/CMakePackage.cmake)